title: "Michigan Mentors Summer CS"

url: "https://wkduggan-umich.github.io"
baseurl: "/MM-Summer-CS-2025"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

logo: "/MM-Summer-CS-2025/img/mm-logo.png"
favicon_ico: "/MM-Summer-CS-2025/img/favicon.ico"

nav_enabled: true
color_scheme: light
